#version: "3.8"
#
#services:
#  receipt-processor:
#    image: receipt-processor:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_PROFILES_ACTIVE: "default"
#    restart: always
#    container_name: receipt-processor

version: '3.8'

services:
  receipt-processor:
    build: .
    container_name: receipt-processor
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
